### PR TITLE
Basic contribution to GSIS ID decoder functions

### PR DESCRIPTION
**Pull request by amogh-dambal**
Hi! My name is Amogh Dambal, and I'm a second-year computer science student at the University of Texas at Austin who is incredibly interested in NFL analytics. I've been reading about and seeing `nflfastR` being used for quite some time, and I just wanted to help and contribute wherever I can. 

I have a little bit of C++ programming knowledge and so wanted to see if I could clean up the implementation of the GSIS ID decoder function. I would love any feedback you could give me.

### CODE REVIEW

**Comment by mrcaseb** [comment]
Thanks for your contribution! The code looks much cleaner than my mess. 

However, I wrote this to maximize performance of decoding and it looks like your code is sigtnificantly slower than the current version. 

nflfastR typically calls gsisdecoder about 40 times with vectors of size about 50k rows. 

The following reprex runs about 3.76 ms with 5000 rows in the current version.

``` r
library(bench)
library(ggplot2)
library(gsisdecoder)

to_decode <- rep(c(
  "32013030-2d30-3033-3338-3733fa30c4fa",
  "NA",
  "00-0033873",
  "NA",
  "32013030-2d30-3032-3739-3434d4d3846d"
), times = 1000)

bm <- bench::mark(old = decode_ids(to_decode), min_iterations = 1000)
bm
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 old          3.54ms   3.76ms      263.    46.3KB        0
autoplot(bm)
#> Lade nötigen Namensraum: tidyr
```



<sup>Created on 2021-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Your code takes about 4.5 ms which is 20% more.

```
 A tibble: 1 x 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result     memory       time        gc          
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>     <list>       <list>      <list>      
1 new          4.29ms    4.5ms      219.    41.6KB        0  1000     0      4.57s <chr [5,0~ <Rprofmem [~ <bench_tm ~ <tibble [1,~
```

grafik


Performance is very important to me in this package so I can't merge this, although the code is much cleaner, as long as it is significantly slower. 

Seb

**Comment by amogh-dambal** [comment]
Thank you so much for the feedback! 

I revisited some parts of my code to make further optimizations, and have pushed the latest version to my repository (there are 4 commits now instead of the original 3). 
I ran the following reprex which you provided on the main `gsisdecoder` package and obtained the following results:
```R
library(bench)
library(ggplot2)
library(gsisdecoder)

to_decode <- rep(c(
  "32013030-2d30-3033-3338-3733fa30c4fa",
  "NA",
  "00-0033873",
  "NA",
  "32013030-2d30-3032-3739-3434d4d3846d"
), times = 1000)

bm <- bench::mark(old = decode_ids(to_decode), min_iterations = 1000)
bm
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch> <bch>     <dbl> <bch:byt>    <dbl>
#> 1 old          3.54ms   3.72ms      263.    46.3KB        0
```

I then used the following code to install my "version" of the package for testing:
```R
install.packages("devtools")
install_github("amogh-dambal/gsisdecoder")
```
and then ran the same reprex, obtaining the following results: 
```R
library(bench)
library(ggplot2)
library(gsisdecoder)

to_decode <- rep(c(
  "32013030-2d30-3033-3338-3733fa30c4fa",
  "NA",
  "00-0033873",
  "NA",
  "32013030-2d30-3032-3739-3434d4d3846d"
), times = 1000)

bm <- bench::mark(old = decode_ids(to_decode), min_iterations = 1000)
bm
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch> <bch>     <dbl> <bch:byt>    <dbl>
#> 1 old          3.25ms   3.4ms      290.    46.3KB        0
```

Please let me know if this testing is correct and/or reproducible; I would very much appreciate any other feedback you have for me! If you would like me to run any other tests, please let me know and I will do so ASAP!
Thank you so much for all of your feedback and your time! 

Amogh

**Comment by mrcaseb** [comment]
Hm this is weird. I don't know why but it's still slower on my machine? Did you run it on a windows PC? Or something else like Mac or Linux?

``` r
library(bench)
library(ggplot2)

to_decode <- rep(c(
  "32013030-2d30-3033-3338-3733fa30c4fa",
  "NA",
  "00-0033873",
  "NA",
  "32013030-2d30-3032-3739-3434d4d3846d"
), times = 1000)

bm <- bench::mark(old = gsisdecoder::decode_ids(to_decode), min_iterations = 1000)
bm
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 old          3.54ms   3.76ms      256.    2.38MB        0
autoplot(bm)
```



``` r
pkgload::load_all(path_to_package)
#> i Loading gsisdecoder

bm <- bench::mark(new = gsisdecoder::decode_ids(to_decode), min_iterations = 1000)
bm
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 new          4.33ms   4.61ms      208.    41.6KB        0
autoplot(bm)
```



<sup>Created on 2021-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mrcaseb** [comment]
If you want to reproduce the benchmark test, please do the following:

1. Install gsisdecoder from cran so you have got version 0.0.1
2. Set your local `path_to_package` in the following code snippet
3. copy the whole code and run `reprex::reprex()`
4. It will run the whole thing in a fresh session using the version 0.0.1 first and then load your updated version second

```r
#+ setup, include = FALSE
path_to_package <- "your local path to the package"

#+ actual-reprex-code
library(bench)
library(ggplot2)

to_decode <- rep(c(
  "32013030-2d30-3033-3338-3733fa30c4fa",
  "NA",
  "00-0033873",
  "NA",
  "32013030-2d30-3032-3739-3434d4d3846d"
), times = 1000)

bm <- bench::mark(old = gsisdecoder::decode_ids(to_decode), min_iterations = 1000)
bm
autoplot(bm)

pkgload::load_all(path_to_package)

bm <- bench::mark(new = gsisdecoder::decode_ids(to_decode), min_iterations = 1000)
bm
autoplot(bm)
```

**Comment by amogh-dambal** [comment]
I ran the code on my Mac; here is the result of running `uname -v` on the machine to give you an idea of the machine specs:
```
% uname -v
# > Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
```
Thank you for providing the code to reproduce the benchmark test! I will run the code you provided exactly.

**Comment by mrcaseb** [comment]
I am not sure if this is just a problem of pkgload tbh. It looks like it's slower when we load the package with pkgload instead of installing it.

**Comment by amogh-dambal** [comment]
I'm having a bit of trouble running reprex example you provided. I installed `gsisdecoder` using CRAN as follows:
```R
install.packages("gsisdecoder")
```
and then set the local path to the package:
```R
path_to_package <- "/Users/.../path/to/package"
```

However, when I then try to run `reprex::reprex()` after copying the script you provided to the clipboard (minus the `path_to_package` variable assignment) as follows:
```R
#+ actual-reprex-code
library(bench)
library(ggplot2)

to_decode <- rep(c(
  "32013030-2d30-3033-3338-3733fa30c4fa",
  "NA",
  "00-0033873",
  "NA",
  "32013030-2d30-3032-3739-3434d4d3846d"
), times = 1000)

bm <- bench::mark(old = gsisdecoder::decode_ids(to_decode), min_iterations = 1000)
bm
autoplot(bm)

pkgload::load_all(path_to_package)

bm <- bench::mark(new = gsisdecoder::decode_ids(to_decode), min_iterations = 1000)
bm
autoplot(bm)
```
I get an error that says "This reprex appears to crash R." Upon further inspection using `rlang::last_error()` and re-running the reprex using `std_out_err = TRUE`, it says:
```
pandoc: unrecognized option --quiet
Error: pandoc document conversion failed with error 2
``` 
and was wondering if you had seen this error before and/or had any ideas about what in the workflow I may be doing incorrectly. 

Additionally, what do you suggest I do in the event that it is a problem with `pkgload`? I checked the GitHub for `pkgload` at https://github.com/r-lib/pkgload, and I couldn't find any helpful documentation about why it might be the case that it's causing a slowdown. 

Thank you so much for your time and for all of your feedback! I am not very experienced with development in R, and so I genuinely appreciate all of your help!

**Comment by mrcaseb** [comment]
I think it's not your fault at all. I tried to compare the performance of the current cran version and your new approach. pkgload loads the complete package in the current session without installing it into your system library. This is very useful for package development. However, I assume that it has not the same performance like really installing it which might be the reason why your code appeared to be slower. 
If I install it and run the benchmark, your new version is slightly faster, which is great!

I have commited some changes to the package infrastructure and will merge it afterwards. Thanks for your contribution!

**Comment by amogh-dambal** [comment]
Sounds awesome, thank you so much! I genuinely appreciate all of your feedback and time, and look forward to contributing more to the `nflverse` in whatever ways I can :D

**Pull request merged**
